project:
  type: book

book:
  title: "Climate Change Informed Species Selection (CCISS) Tool"
  author: "FFEC"
  date: "2025-06-04"
  chapters:
    - index.qmd
    - Overview.qmd
    - Instructions.qmd
    - Methods.qmd
    - Issues.qmd
    - Decisions.qmd
    - Feedback.qmd
    - FAQs.qmd
    - Resources.qmd


bibliography: references.bib

format:
  html:
    css: style.css
    toc: true
    toc-depth: 3
    number-sections: true
    theme: cosmo  # or null if you're using a custom theme
    search: true  # built-in search bar

editor: visual

